### ISSUE TITLE
error: no matching package named `c2rust-asm-casts` found

### ISSUE THREAD

**Issue by samuela** [immunant/c2rust#189]
I'm working on transpiling an existing codebase
```
c2rust transpile --binary myprogram compile_commands.json
```
but it's generating a `Cargo.toml` file that looks like
```toml
[workspace]
members = [
]

[package]
name = "c2rust"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[lib]
name = "c2rust"
path = "c2rust-lib.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
c2rust-bitfields = "0.3"
c2rust-asm-casts = "0.1"
libc = "0.2"
```
which would be fine except that cargo cannot find a package named `c2rust-asm-casts`.
